//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormData
    {
        public int Id { get; set; }
        public Nullable<int> FormId { get; set; }
        public string DataJSON { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Deletedby { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual FormInfo FormInfo { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
