//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormInfo()
        {
            this.FormDatas = new HashSet<FormData>();
        }
    
        public int Id { get; set; }
        public string FormName { get; set; }
        public string FormJSON { get; set; }
        public string FormTitle { get; set; }
        public string FormType { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormData> FormDatas { get; set; }
    }
}
